server:
    port: 8090
    
spring:
 application:
    name: articleDiscover
    Desc: retrievs article data by articleNo
    
 datasource:
   url: jdbc:mysql://mysql-container:3306/tola
   username: root
   password: Tasnim2017#
   driver-class-name: com.mysql.cj.jdbc.Driver
   hikari.connection-timeout: 30000
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    
origins: "http://localhost:3000"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

