server:
    port: 8090
    
spring:
 application:
    name: articleDiscover
    Desc: retrievs article data by articleNo
    
 main:
   web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

