name : Build & Deploy articleDiscove app

on:
  push:
    branches:
      - master
      
jobs:
  build-deploy:
    name:  Build & Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 8
         
      - name: Unit Tests   
        run: mvn -B test --file pom.xml -Dmaven.repo.local=$HOME/.m2/repository
         
      - name: Build the application
        run: 
          mvn clean
          mvn -B package --file pom.xml -Dmaven.repo.local=$HOME/.m2/repository    
    