name : Build & Deploy articleDiscove app

on:
  push:
    branches:
      - master
      
jobs:
  build-deploy:
    name:  Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#        with:
#          ssh-key: SHA256:ms6Xxtf1yEd2R0PFPhsoS5ODiHlxS4s7c+4pNBDxHmg
#
#          submodules: true
          
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '1.8'
         
      - name: Unit Tests   
        run: mvn -B test --file pom.xml
         
      - name: Build the application
        run: 
          mvn clean
          mvn -B package --file pom.xml      
    